import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Nav from "./components/nav/page.js";
import WhatsAppButton from "./components/whatsapp/page.js"
import Footer from "./components/footer/page.js"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mindtree Nursing Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html
    
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<body className="min-h-full flex flex-col"> 
        
       {/*head*/}   


      <Nav />
  
        {children}       
          <WhatsAppButton phoneNumber="919876543210" message="Hello, I'd like to know more about your services." />
    
        <Footer/>
       
        </body>
      
    </html>
  );
}
